export const grammar = {
    nonTerminals: [
        "<expr>",
        "<term>",
        "<factor>",
        "<digit>",
        "<letter>"
    ],
    terminals: ["+", "-", "*", "/", "(", ")", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
    productions: [
        ["<expr>", "<expr>+<term>"],
        ["<expr>", "<expr>-<term>"],
        ["<expr>", "<expr>*<expr>"],
        ["<expr>", "<expr>/<expr>"],
        ["<expr>", "<term>"],
        ["<expr>", "<term>*<factor>"],
        ["<expr>", "<term>/<factor>"],
        ["<term>", "<term>*<factor>"],
        ["<term>", "<term>/<factor>"],
        ["<term>", "<factor>"],
        ["<factor>", "(<expr>)"],
        ["<factor>", "<digit>"],
        ["<factor>", "<letter>"],
        ["<digit>", "0"],
        ["<digit>", "1"],
        ["<digit>", "2"],
        ["<digit>", "3"],
        ["<digit>", "4"],
        ["<digit>", "5"],
        ["<digit>", "6"],
        ["<digit>", "7"],
        ["<digit>", "8"],
        ["<digit>", "9"],
        ["<letter>", "a"],
        ["<letter>", "b"],
        ["<letter>", "c"],
        ["<letter>", "d"],
        ["<letter>", "e"],
        ["<letter>", "f"],
        ["<letter>", "g"],
        ["<letter>", "h"],
        ["<letter>", "i"],
        ["<letter>", "j"],
        ["<letter>", "k"],
        ["<letter>", "l"],
        ["<letter>", "m"],
        ["<letter>", "n"],
        ["<letter>", "o"],
        ["<letter>", "p"],
        ["<letter>", "q"],
        ["<letter>", "r"],
        ["<letter>", "s"],
        ["<letter>", "t"],
        ["<letter>", "u"],
        ["<letter>", "v"],
        ["<letter>", "w"],
        ["<letter>", "x"],
        ["<letter>", "y"],
        ["<letter>", "z"],
        ["<letter>", "A"],
        ["<letter>", "B"],
        ["<letter>", "C"],
        ["<letter>", "D"],
        ["<letter>", "E"],
        ["<letter>", "F"],
        ["<letter>", "G"],
        ["<letter>", "H"],
        ["<letter>", "I"],
        ["<letter>", "J"],
        ["<letter>", "K"],
        ["<letter>", "L"],
        ["<letter>", "M"],
        ["<letter>", "N"],
        ["<letter>", "O"],
        ["<letter>", "P"],
        ["<letter>", "Q"],
        ["<letter>", "R"],
        ["<letter>", "S"],
        ["<letter>", "T"],
        ["<letter>", "U"],
        ["<letter>", "V"],
        ["<letter>", "W"],
        ["<letter>", "X"],
        ["<letter>", "Y"],
        ["<letter>", "Z"]
    ],
    startSymbol: "<expr>"
};